### ISSUE TITLE
‘ttservice’ 0.2.2 was found, but >= 0.3.6 is required. But 0.4 is on CRAN

### ISSUE THREAD

**Issue by stemangiola** [neurogenomics/rworkflows#129]
Hello,

thanks again for your package.

I get the error

https://github.com/stemangiola/tidybulk/actions/runs/7812323101/job/21309136797

```r
‘ttservice’ 0.2.2 was found, but >= 0.3.6 is required
```

But ttservice 0.4 is on CRAN!

https://cran.r-project.org/web/packages/ttservice/index.html

I am not sure why the Github action looks for an old CRAN mirror (?)

**Comment by stemangiola** [comment]
Sorry this error is not from you github actions.

**Comment by bschilder** [comment]
> Sorry this error is not from you github actions.

No worries, good to know anyways!
