### ISSUE TITLE
Submit to CRAN or Bioc

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#18]
Even though the R package component is currently fairly minimalist, would be good to submit to CRAN or Bioc.
Might consider adding some functions from `echogithub`, eg `readme_header`:
https://github.com/RajLabMSSM/echogithub

**Comment by NathanSkene** [comment]
Are there standalone R package parts?

From: Brian M. Schilder ***@***.***>
Date: Monday, 14 November 2022 at 23:01
To: neurogenomics/rworkflows ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neurogenomics/rworkflows] Submit to CRAN or Bioc (Issue #18)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Even though the R package component is currently fairly minimalist, would be good to submit to CRAN or Bioc.
Might consider adding some functions from echogithub, eg readme_header:
https://github.com/RajLabMSSM/echogithub

**Comment by bschilder** [comment]
> Are there standalone R package parts? 

Yes! Here's fig 1 atm:
![fig1](https://user-images.githubusercontent.com/34280215/201977371-472d2fe1-0483-4f82-a355-47290f2697e6.png)

**Comment by lcolladotor** [comment]
Give it a try at BioC first. Likely @link-ny will be the assigned reviewer.

**Comment by lcolladotor** [comment]
and/or @grimbough

**Comment by bschilder** [comment]
@lcolladotor I'd normally go for Bioc first, but I'd like to have `rworkflows` reach the broadest audience possible, including those outside of biology or even the natural sciences. So I'm thinking CRAN might be the way to go for that reason.

**Comment by lcolladotor** [comment]
sounds good!

**Comment by bschilder** [comment]
Submitted to CRAN today! Awaiting review

**Comment by bschilder** [comment]
`rworkflows` is now on CRAN!
https://cran.r-project.org/web/packages/rworkflows/
