### ISSUE TITLE
Synchronise R/Bioc versions

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/rworkflows#33]
Originally posted here by @mtmorgan:
https://github.com/Bioconductor/Rsamtools/pull/48#issuecomment-1364025988
> I'm also not confident that the workflow is 'doing the right thing' and will continue to do the right thing, with respect to versioning. For instance the Linux distribution appears to use R-devel and bioconductor/bioconductor_docker:devel, which is correct for the current and next Bioconductor release cycle, but will be incorrect for the cycle after that (bioconductor has a twice yearly release cycle whereas R has an annual cycle; bioconductor devel anticipates the user environment when it becomes release, so bioc-devel only builds on R-devel 1/2 the time). Likewise macOS and Windows seem to be using R 'latest' but bioc-devel, which is not how Bioconductor distributes packages.

I'd like to programmatically extract the 'correct' versions for R and Bioc such that they match the Bioc release schedule, so that users never have to worry about that.

**Comment by mtmorgan** [comment]
The information is available in https://bioconductor.org/config.yaml

**Comment by bschilder** [comment]
This has now been implemented in a couple ways. See here:
#16 
#19 
#20

**Comment by bschilder** [comment]
The new function `rworkflows::bioc_r_versions()` also helps with this when creating workflows, as it grabs the versions that "devel" and "release" are referring to currently using the [yaml link](https://github.com/neurogenomics/rworkflows/issues/33#issuecomment-1364056921) provided by @mtmorgan 

By default, Linux uses Bioc devel , while Mac and Windows use Bioc release. In all cases, the correct version of R is installed (albeit via a different, container-based approach on Linux). 

Rather than having the Bioc version used in your workflow change whenever Bioc makes a new release, users can choose to hard-code the appropriate version numbers into the workflow:
```R
runners <- rworkflows::construct_runners(versions_explicit = TRUE)
rworkflows::use_workflow(runners= runners)

print(runners)
```
```R

[[1]]
[[1]]$os
[1] "ubuntu-latest"

[[1]]$bioc
[1] ‘3.17’

[[1]]$r
[1] ‘4.2.0’

[[1]]$cont
[1] "bioconductor/bioconductor_docker:devel"

[[1]]$rspm
[1] "https://packagemanager.rstudio.com/cran/__linux__/focal/release"


[[2]]
[[2]]$os
[1] "macOS-latest"

[[2]]$bioc
[1] ‘3.16’

[[2]]$r
[1] ‘4.2.0’

[[2]]$cont
NULL

[[2]]$rspm
NULL


[[3]]
[[3]]$os
[1] "windows-latest"

[[3]]$bioc
[1] ‘3.16’

[[3]]$r
[1] ‘4.2.0’

[[3]]$cont
NULL

[[3]]$rspm
NULL

```
