### ISSUE TITLE
Depgraph vignette unreadable font color

### ISSUE THREAD

**Issue by OskarGauffin** [neurogenomics/rworkflows#47]
A very minor thing, but this is the depgraph vignette on my Android device:

![Screenshot_20230201-152648.png](https://user-images.githubusercontent.com/7349924/216072032-32672fc3-2697-492a-ae9f-b9fa9fca037e.png)

**Comment by bschilder** [comment]
thanks for letting me know about this! the background color of the visNetwork is somehow getting propagated to the rest of the vignette. I'll set a white background as the default.

Best, 
Brian

**Comment by bschilder** [comment]
Made a bunch of other enhancements to `echodeps` (hover metadata/links, hex symbols, scraping actions dependants from multiple pages) and changed the background color.
https://neurogenomics.github.io/rworkflows/articles/depgraph.html

![Screenshot 2023-03-14 at 17 52 28](https://user-images.githubusercontent.com/34280215/225094724-8a15eedf-133e-41d7-bb4d-f25307b5905e.png)
