### ISSUE TITLE
`trying to use CRAN without setting a mirror` on mac and windows runners

### ISSUE THREAD

**Issue by AliSajid** [neurogenomics/rworkflows#72]
## 1. Bug description

I am running into the same error as #13 (trying to use CRAN without setting a mirror) but only on the macOS and windows runners. This does not happen on the ubuntu-latest.

### Console output 

```
Chocolatey installed 3/3 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Run download.file('https://bioconductor.org/checkResults/release/bioc-LATEST/Renviron.bioc', destfile = '~/.Renviron', mode = 'wb')
trying URL 'https://bioconductor.org/checkResults/release/bioc-LATEST/Renviron.bioc'
Content type 'unknown' length 3131 bytes
==================================================
downloaded 3131 bytes

Run write('options(BioC_mirror = "https://www.bioconductor.org/")', file = '~/.Rprofile', append = TRUE)
Run install.packages(c("BiocManager", "remotes"), quiet = TRUE)
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted
Error: Process completed with exit code 1.
Run actions/upload-artifact@v3
Warning: No files were found with the provided path: check. No artifacts will be uploaded.


```

### Expected behaviour   

Run completes successfully

**Comment by AliSajid** [comment]
Bumping this for visibility

**Comment by bschilder** [comment]
Hi @AliSajid sorry for the delay, been traveling. Looking into this now

**Comment by AliSajid** [comment]
Hi,

Thank you for looking into this. Here's the most recent run: https://github.com/CogDisResLab/drugfindR/actions/runs/6161263399

**Comment by bschilder** [comment]
Ok, I think this might be occurring within the `bioc-actions/setup-bioc` action. @grimbough have you noticed something like this on your end lately?

https://github.com/grimbough/bioc-actions/blob/v1-branch/setup-bioc/action.yml

**Comment by bschilder** [comment]
Possibly related issues;

https://stackoverflow.com/a/68706205
https://github.com/r-lib/actions/issues/559

**Comment by bschilder** [comment]
@AliSajid in trying to spot any differences between my repos and yours, I found that you committed the `.Rprofile` file. Some other posts suggest that this can cause issues in certain contexts (tho it's not clear if these relate to this particular issue):
https://github.com/r-lib/actions/issues/754

If you don't mind, could I ask you to try out the following?:
Remove your `.Rprofile` from GitHub, and then running GHA again:
```
git rm --cached .Rprofile
```

If this works, you'll want to add `.Rprofile` to your `.gitignore` too.

**Comment by AliSajid** [comment]
@bschilder In a manner I can not understand, removing `.Rprofile` did solve the issue. I've added it to my `.gitignore`. Although, I am surprised that this caused an issue as I frequently commit my `.Rprofile` which has only these contents:

```
if (file.exists("~/.Rprofile")) {
    if (interactive()) {
        source("~/.Rprofile") # nolint: undesirable_function_linter.
    }
}
source("renv/activate.R") # nolint: undesirable_function_linter.

```

And have not seen any issue.


Thank you. I really appreciate your work and your time.

**Comment by bschilder** [comment]
> @bschilder In a manner I can not understand, removing `.Rprofile` did solve the issue. I've added it to my `.gitignore`. Although, I am surprised that this caused an issue as I frequently commit my `.Rprofile` which has only these contents:
> 
> ```
> if (file.exists("~/.Rprofile")) {
>     if (interactive()) {
>         source("~/.Rprofile") # nolint: undesirable_function_linter.
>     }
> }
> source("renv/activate.R") # nolint: undesirable_function_linter.
> ```
> 
> And have not seen any issue.
> 
> Thank you. I really appreciate your work and your time.

Great! Glad to hear it worked.

I'm not sure I fully understand why this would resolve it either, but I'll try to delve into this more to get to the root of it and add some additional safeguards to `rworkflows` so users don't encounter this issue.
